apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: <your-docker-registry>/node-app:latest # Replace with your Docker image location
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: postgres-service # This should match the service name for PostgreSQL
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer # Exposes the service to the internet
