# Use a specific version of the PostgreSQL image
FROM postgres:15

# Copy initialization SQL script into the Docker image
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432
