apiVersion: v1
kind: Pod
metadata:
  name: debug-postgres
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"] # Keeps the pod running for 1 hour
      volumeMounts:
        - name: postgres-storage
          mountPath: /mnt/data
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
