apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: RGV0dGUlRXIlRXR0JUxhbmd0JW9nJVZhbnNrZWxpZyVQYXNzb3JkITEyMw==
  #POSTGRES_PASSWORD: bWl0dHBhc3NvcmQ= #mittpassord
  POSTGRES_DB: aGVsdmVkX2Ri
