name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2  # Ensure you are using the correct version
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Use github.actor for the username
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Pull official PostgreSQL image
        run: |
          docker pull postgres:latest
          docker tag postgres:latest ghcr.io/${{ github.repository_owner }}/postgres:latest
          docker push ghcr.io/${{ github.repository_owner }}/postgres:latest

      - name: Build and push Node.js Docker image
        run: |
          IMAGE_TAG=jancoach_api:$(date +%s)
          docker build . --file Dockerfile.node --tag ghcr.io/${{ github.repository_owner }}/${IMAGE_TAG}
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_TAG}