name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: bild first docker image
      env:
        IMAGE_NAME_1: postgres
      run: |
        docker build . --file Dockerfile.postgres --tag postgres:18

    - name: Build and push second Docker image
      env:
        IMAGE_NAME_2: node
      run: |
        docker build . --file Dockerfile.node --tag node:$(date +%s).
        docker push node
