name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

        env:
          IMAGE_NAME_1: postgres
        run: |
          docker build . --file Dockerfile.postgres --tag postgres:$(date +%s)

      - name: Build and push second Docker image
        env:
          IMAGE_NAME_2: node
        run: |
          docker build . --file Dockerfile.node --tag node:$(date +%s).
          docker push node
