name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build first Docker image
        run: |
          docker build . --file Dockerfile.postgres --tag ghcr.io/${{ github.repository_owner }}/postgres:18
          docker push ghcr.io/${{ github.repository_owner }}/postgres:18

      - name: Build and push second Docker image
        run: |
          IMAGE_TAG=node:$(date +%s)
          docker build . --file Dockerfile.node --tag ghcr.io/${{ github.repository_owner }}/${IMAGE_TAG}
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_TAG}




